name: My First Workflow #name of this workflow

# trigger - This workflow will run whenever the repo receives a push
# on: [push] OR
on: 
- push
# - pull

# Jobs to perform in the workflow
jobs:

  #job's id/ name
  my-first-workflow:  

    # OS that this job will be running on
    runs-on: ubuntu-latest  #key: value

    # list of steps to perform task
    steps:
    - name: echo the date
      run: echo "The current time and date in GitHub is $(date)"
    - name: echo information about the context
      run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"
    - name: List runner name
      run: echo "runner os - $ {{ runner.os }}"
    #- name: failing on purpose  #failing the workflow
      #run: fail()  
    - name: Echo my secret  #if incorrect, no error but get nothing
      run: echo "MY_SECRET" is ${{ secrets.MY_SECRET }}"